//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagementSystem {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StudentManagementSystem.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Dashboard.
        /// </summary>
        internal static string AdminDashboard {
            get {
                return ResourceManager.GetString("AdminDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter values in all fields!.
        /// </summary>
        internal static string AllFieldsWarning {
            get {
                return ResourceManager.GetString("AllFieldsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Grades.
        /// </summary>
        internal static string AllGradesLabel {
            get {
                return ResourceManager.GetString("AllGradesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Athlete Students Information.
        /// </summary>
        internal static string AthleteInfoHeader {
            get {
                return ResourceManager.GetString("AthleteInfoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose course to view:.
        /// </summary>
        internal static string ChooseCourse {
            get {
                return ResourceManager.GetString("ChooseCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string ClearBtn {
            get {
                return ResourceManager.GetString("ClearBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string contactLabel {
            get {
                return ResourceManager.GetString("contactLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses.
        /// </summary>
        internal static string CoursesColumn {
            get {
                return ResourceManager.GetString("CoursesColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses.
        /// </summary>
        internal static string coursesLabel {
            get {
                return ResourceManager.GetString("coursesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses taught.
        /// </summary>
        internal static string CoursesTaught {
            get {
                return ResourceManager.GetString("CoursesTaught", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an account.
        /// </summary>
        internal static string CreateAccountLink {
            get {
                return ResourceManager.GetString("CreateAccountLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        internal static string CreateBtn {
            get {
                return ResourceManager.GetString("CreateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        internal static string CreateFormTitle {
            get {
                return ResourceManager.GetString("CreateFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create student.
        /// </summary>
        internal static string CreateStudentTitle {
            get {
                return ResourceManager.GetString("CreateStudentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing provided in feedback!.
        /// </summary>
        internal static string EmptyFeedback {
            get {
                return ResourceManager.GetString("EmptyFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Student ID.
        /// </summary>
        internal static string EnterStudentID {
            get {
                return ResourceManager.GetString("EnterStudentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your username:.
        /// </summary>
        internal static string EnterUsername {
            get {
                return ResourceManager.GetString("EnterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        internal static string FeedbackLabel {
            get {
                return ResourceManager.GetString("FeedbackLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback was sent to the student!.
        /// </summary>
        internal static string FeedbackSent {
            get {
                return ResourceManager.GetString("FeedbackSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name:.
        /// </summary>
        internal static string firstNameLabel {
            get {
                return ResourceManager.GetString("firstNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students List.
        /// </summary>
        internal static string FullTimeGroupBox {
            get {
                return ResourceManager.GetString("FullTimeGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Full Time Students.
        /// </summary>
        internal static string FullTimeTitle {
            get {
                return ResourceManager.GetString("FullTimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPA.
        /// </summary>
        internal static string gpaLabel {
            get {
                return ResourceManager.GetString("gpaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        internal static string GradeColumn {
            get {
                return ResourceManager.GetString("GradeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grades Information.
        /// </summary>
        internal static string GradesInfo {
            get {
                return ResourceManager.GetString("GradesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Information.
        /// </summary>
        internal static string GroupBoxAccountInfo {
            get {
                return ResourceManager.GetString("GroupBoxAccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        internal static string GroupBoxPersonalInfo {
            get {
                return ResourceManager.GetString("GroupBoxPersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Search.
        /// </summary>
        internal static string grpQuickSearchGroupBox {
            get {
                return ResourceManager.GetString("grpQuickSearchGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Header_Address {
            get {
                return ResourceManager.GetString("Header_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency Contact.
        /// </summary>
        internal static string Header_Contact {
            get {
                return ResourceManager.GetString("Header_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Header_Name {
            get {
                return ResourceManager.GetString("Header_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student ID.
        /// </summary>
        internal static string Header_StudentID {
            get {
                return ResourceManager.GetString("Header_StudentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Type.
        /// </summary>
        internal static string Header_StudentType {
            get {
                return ResourceManager.GetString("Header_StudentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Fields.
        /// </summary>
        internal static string InvalidFieldsTitle {
            get {
                return ResourceManager.GetString("InvalidFieldsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid numeric Student ID..
        /// </summary>
        internal static string InvalidID {
            get {
                return ResourceManager.GetString("InvalidID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string LabelAddress {
            get {
                return ResourceManager.GetString("LabelAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact #.
        /// </summary>
        internal static string LabelContact {
            get {
                return ResourceManager.GetString("LabelContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course.
        /// </summary>
        internal static string LabelCourses {
            get {
                return ResourceManager.GetString("LabelCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string LabelName {
            get {
                return ResourceManager.GetString("LabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Type.
        /// </summary>
        internal static string LabelStudentType {
            get {
                return ResourceManager.GetString("LabelStudentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher.
        /// </summary>
        internal static string LabelTeacher {
            get {
                return ResourceManager.GetString("LabelTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher ID.
        /// </summary>
        internal static string LabelTeacherID {
            get {
                return ResourceManager.GetString("LabelTeacherID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name:.
        /// </summary>
        internal static string lastNameLabel {
            get {
                return ResourceManager.GetString("lastNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string LoginBtn {
            get {
                return ResourceManager.GetString("LoginBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login error.
        /// </summary>
        internal static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful login!.
        /// </summary>
        internal static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect username or password!.
        /// </summary>
        internal static string LoginWelcome {
            get {
                return ResourceManager.GetString("LoginWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Tracking.
        /// </summary>
        internal static string MenuAcademicTracking {
            get {
                return ResourceManager.GetString("MenuAcademicTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Athletes Student.
        /// </summary>
        internal static string MenuAthletesStudent {
            get {
                return ResourceManager.GetString("MenuAthletesStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Student.
        /// </summary>
        internal static string MenuCreateStudent {
            get {
                return ResourceManager.GetString("MenuCreateStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Teacher.
        /// </summary>
        internal static string MenuCreateTeacher {
            get {
                return ResourceManager.GetString("MenuCreateTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullTime Student.
        /// </summary>
        internal static string MenuFullTimeStudent {
            get {
                return ResourceManager.GetString("MenuFullTimeStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Student.
        /// </summary>
        internal static string MenuManageStudent {
            get {
                return ResourceManager.GetString("MenuManageStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartTime Student.
        /// </summary>
        internal static string MenuPartTimeStudent {
            get {
                return ResourceManager.GetString("MenuPartTimeStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Management.
        /// </summary>
        internal static string MenuStudentManagement {
            get {
                return ResourceManager.GetString("MenuStudentManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher Management.
        /// </summary>
        internal static string MenuTeacherManagement {
            get {
                return ResourceManager.GetString("MenuTeacherManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        internal static string NoAccountLabel {
            get {
                return ResourceManager.GetString("NoAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (no feedback yet).
        /// </summary>
        internal static string NoFeedback {
            get {
                return ResourceManager.GetString("NoFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Time Students Information.
        /// </summary>
        internal static string PartTimeInfoHeader {
            get {
                return ResourceManager.GetString("PartTimeInfoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grades were updated if provided!.
        /// </summary>
        internal static string ProvidedGrades {
            get {
                return ResourceManager.GetString("ProvidedGrades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Athletes.
        /// </summary>
        internal static string RadioAthletes {
            get {
                return ResourceManager.GetString("RadioAthletes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full-Time.
        /// </summary>
        internal static string RadioFullTime {
            get {
                return ResourceManager.GetString("RadioFullTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part-Time.
        /// </summary>
        internal static string RadioPartTime {
            get {
                return ResourceManager.GetString("RadioPartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveBtn {
            get {
                return ResourceManager.GetString("SaveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchBtn {
            get {
                return ResourceManager.GetString("SearchBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string searchButton {
            get {
                return ResourceManager.GetString("searchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string SearchID {
            get {
                return ResourceManager.GetString("SearchID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send feedback.
        /// </summary>
        internal static string SendFeedbackButton {
            get {
                return ResourceManager.GetString("SendFeedbackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Information.
        /// </summary>
        internal static string StudentInfo {
            get {
                return ResourceManager.GetString("StudentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        internal static string StudentListLabel {
            get {
                return ResourceManager.GetString("StudentListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student not found..
        /// </summary>
        internal static string StudentNotFound {
            get {
                return ResourceManager.GetString("StudentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studenrt Profile View.
        /// </summary>
        internal static string StudentProfileView {
            get {
                return ResourceManager.GetString("StudentProfileView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student was successfully saved!.
        /// </summary>
        internal static string StudentSaved {
            get {
                return ResourceManager.GetString("StudentSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher and Courses.
        /// </summary>
        internal static string TeacherCourseInfo {
            get {
                return ResourceManager.GetString("TeacherCourseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created the teacher!.
        /// </summary>
        internal static string TeacherCreated {
            get {
                return ResourceManager.GetString("TeacherCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher Dashboard.
        /// </summary>
        internal static string TeacherDashboardTitle {
            get {
                return ResourceManager.GetString("TeacherDashboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher Profile.
        /// </summary>
        internal static string TeacherProfile {
            get {
                return ResourceManager.GetString("TeacherProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string ThemeBtn {
            get {
                return ResourceManager.GetString("ThemeBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Management System.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update grades.
        /// </summary>
        internal static string UpdateGradesButton {
            get {
                return ResourceManager.GetString("UpdateGradesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID:.
        /// </summary>
        internal static string UserIDLabel {
            get {
                return ResourceManager.GetString("UserIDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already exists!.
        /// </summary>
        internal static string UsernameExists {
            get {
                return ResourceManager.GetString("UsernameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username Exists Error.
        /// </summary>
        internal static string UsernameExistsTitle {
            get {
                return ResourceManager.GetString("UsernameExistsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string UsernameLabel {
            get {
                return ResourceManager.GetString("UsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string WelcomeLabel {
            get {
                return ResourceManager.GetString("WelcomeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
    }
}
